---
- hosts: all
  become: true

  tasks:

    - name: create docker cfg directory
      file:
        path: /etc/docker
        state: directory
        mode: '0755'
    
    - name: put docker network config files
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Set timezone to NSK
      timezone:
        name: Asia/Novosibirsk

    - name: Allow specified groups to sudo
      template: 
        src: sudoers.j2
        dest: /etc/sudoers.d/yagza
        validate: 'visudo -cf %s'
        mode: 0440

    - name: install curl and stuff
      package:
        name: curl,wget,chrony,epel-release,bash-completion-extras,git
        state: present
        update_cache: yes

    - name: install docker
      shell: curl -sSL https://get.docker.com/ | sh

    - name: install compose
      package:
        name: docker-compose
        state: present
        update_cache: yes

    - name: make docker rootless
      user: 
        name: yagza
        groups: docker
        append: 'yes'

    - name: start chrony
      service: 
        name: chronyd
        state: restarted
        enabled: yes

    - name: start docker
      service: 
        name: docker
        state: started
        enabled: yes

    - name: stop firewall
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: clone Bret Fisher udemy resources
      git:
        repo: https://github.com/BretFisher/udemy-docker-mastery.git
        dest: udemy-docker-mastery


