---

- name: Start all vms
  hosts: all
  tasks:

  - name: Start vm 1
    virt:
      name: doc1
      state: shutdown

  - name: Start vm 2
    virt:
      name: doc2
      state: shutdown

  - name: Start vm 3
    virt:
      name: doc3
      state: shutdown

  - name: get status of vms
    virt:
      command: list_vms

